{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opa.serviceAccountName" .}}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . }}
  {{- end }}
  labels:
    app: {{ template "opa.fullname" . }}
    chart: {{ template "opa.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opa.serviceAccountName" .}}-kube-admin-api-{{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opa.serviceAccountName" .}}-kube-admin-api-{{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "opa.serviceAccountName" .}}-kube-admin-api-{{ .Release.Namespace }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "opa.serviceAccountName" .}}-kube-admin-api-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "opa.serviceAccountName" .}}-kube-admin-api-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
